name: Automated browser tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Install deps    
        run: npm install --save-dev @types/jest
      - name: run tests
        run: npm run test
