name: Automated browser tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: init
      run: npm init
    - name: install dep
      run: npm install
    - name: run test
      run: npm run test
